### ISSUE TITLE
To Dos and general information

### ISSUE THREAD

**Issue by valafeli** [valafeli/SPL#1]
# **South African Heart Disease Study**

- [hier ](https://github.com/settings/notifications) könnt Ihr Eure Benachrichtigungseinstellung ändern, wobei es in diesem Reiter (Issues) eine seperate Benachrichtigungseinstellung gibt...
- mit dem Programm kann man ganz in Ruhe auf seinem Rechner z.B. mit R-Studio arbeiten und sobald an der Datei ne Änderung vorgenommen wurde, wird Dir im GitHub-Programm vorgeschlagen, zu "pushen"... Also Deine (auf Deinem Rechner) gemachten Änderung hochzuladen... das Git-Hub Programm gleich auch alle paar  Sekunden/Minuten den Onlinestand ab... wenn dort ne Änderung neu ist, kannst Du "pullen", um die neuen Dateien/Dateiänderungen auf Deinem Rechner zu haben...
- @rolfad: Hier zu schreiben scheint mit am sinnvollsten zu sein...

1.  Introduction
2. Data Preparation
3. Descripive Statistics
4. Logistic Regression
5. Cross Validation
6. Scoring
7. Interpretation and Conclusion

### Descriptive Statistics
[Link](www.math.chalmers.se/Stat/Grundutb/GU/MSG500/A09/RegSummary09.pdf)

### Logistic Regression 
[Link](https://gist.github.com/smc77/1315162/00727351f7e150a3f5ddb7fdfb696715ea1a545b)

### Cross Validation
[Link](http://www.milanor.net/blog/cross-validation-for-predictive-analytics-using-r/)

### Scoring
[Link](http://rstudio-pubs-static.s3.amazonaws.com/5267_0156db47a0604aa9818143e7d2db226e.html)

**Comment by valafeli** [comment]
[](https://gist.github.com/smc77/1315162/00727351f7e150a3f5ddb7fdfb696715ea1a545b)

**Comment by valafeli** [comment]
[Logistic Regression](https://gist.github.com/smc77/1315162/00727351f7e150a3f5ddb7fdfb696715ea1a545b)

**Comment by bargellu** [comment]
http://archive.samj.org.za/1983%20VOL%20LXIV%20%20Jul-Dec/Articles/09%20September/3.6%20REVIEW%20ARTICLE%20-%20DIET%20AND%20HEART%20DISEASE%20IN%20THE%201980's.%20J.E.%20Rossouw.pdf

**Comment by bargellu** [comment]
"These data are taken from a larger dataset, described in Rousseauw et al, 1983, South African. Medical Journal. "

**Comment by bargellu** [comment]
4.4.2 Example: South African Heart Disease
Here we present an analysis of binary data to illustrate the traditional statistical use of the logistic regression model. The data in Figure 4.12 are a subset of the Coronary Risk-Factor Study (CORIS) baseline survey, carried out in three rural areas of the Western Cape, South Africa (Rousseauw et al., 1983). The aim of the study was to establish the intensity of ischemic heart disease risk factors in that high-incidence region. The data represent white males between 15 and 64, and the response variable is the presence or absence of myocardial infarction (MI) at the time of the survey (the overall prevalence of MI was 5.1% in this region). There are 160 cases in our data set, and a sample of 302 controls. These data are described in more detail in Hastie and Tibshirani (1987).

**Comment by bargellu** [comment]
http://archive.samj.org.za/1983%20VOL%20LXIV%20%20Jul-Dec/Articles/09%20September/35CORO~1.PDF

Richtige Schreibweise: **_Rossouw_**

**Comment by bargellu** [comment]
http://archive.samj.org.za/index.php?path=%2F1983+VOL+LXIV++Jul-Dec%2FArticles%2F09+September

Der richtige Artikel ist der zweite von unten under 35CORO-1.PDF

Nicht richtig beschriftet also... ;-)

**Comment by valafeli** [comment]
# Apply logistic regression to South African heart data from ESL
> sa.heart.fit <- glm(chd ~ ., family = binomial, data=SAheart)
> summary(sa.heart.fit)

Call:
glm(formula = chd ~ ., family = binomial, data = SAheart)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.7781  -0.8213  -0.4387   0.8889   2.5435  

Coefficients:
                 Estimate Std. Error z value Pr(>|z|)    
(Intercept)    -6.1507209  1.3082600  -4.701 2.58e-06 ***
sbp             0.0065040  0.0057304   1.135 0.256374    
tobacco         0.0793764  0.0266028   2.984 0.002847 ** 
ldl             0.1739239  0.0596617   2.915 0.003555 ** 
adiposity       0.0185866  0.0292894   0.635 0.525700    
famhistPresent  0.9253704  0.2278940   4.061 4.90e-05 ***
typea           0.0395950  0.0123202   3.214 0.001310 ** 
obesity        -0.0629099  0.0442477  -1.422 0.155095    
alcohol         0.0001217  0.0044832   0.027 0.978350    
age             0.0452253  0.0121298   3.728 0.000193 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 596.11  on 461  degrees of freedom
Residual deviance: 472.14  on 452  degrees of freedom
AIC: 492.14

Number of Fisher Scoring iterations: 5

> 
> # Use stepwise logistic regression to reduce the dimensions
> library(MASS)
> sa.heart.step <- stepAIC(glm(chd ~ ., data=SAheart))
Start:  AIC=522.41
chd ~ sbp + tobacco + ldl + adiposity + famhist + typea + obesity + 
    alcohol + age

            Df Deviance    AIC
- alcohol    1   79.919 520.49
- adiposity  1   79.945 520.65
- sbp        1   80.187 522.04
<none>           79.904 522.41
- obesity    1   80.350 522.98
- typea      1   81.480 529.43
- ldl        1   81.612 530.18
- tobacco    1   81.962 532.16
- age        1   82.002 532.38
- famhist    1   83.025 538.11

Step:  AIC=520.49
chd ~ sbp + tobacco + ldl + adiposity + famhist + typea + obesity + 
    age

            Df Deviance    AIC
- adiposity  1   79.957 518.72
- sbp        1   80.192 520.07
<none>           79.919 520.49
- obesity    1   80.362 521.05
- typea      1   81.483 527.45
- ldl        1   81.677 528.55
- tobacco    1   81.979 530.25
- age        1   82.035 530.57
- famhist    1   83.025 536.11

Step:  AIC=518.72
chd ~ sbp + tobacco + ldl + famhist + typea + obesity + age

          Df Deviance    AIC
- sbp      1   80.248 518.40
<none>         79.957 518.72
- obesity  1   80.490 519.79
- typea    1   81.491 525.50
- ldl      1   81.921 527.93
- tobacco  1   82.025 528.51
- famhist  1   83.063 534.32
- age      1   83.232 535.26

Step:  AIC=518.4
chd ~ tobacco + ldl + famhist + typea + obesity + age

          Df Deviance    AIC
<none>         80.248 518.40
- obesity  1   80.686 518.91
- typea    1   81.736 524.89
- ldl      1   82.223 527.63
- tobacco  1   82.396 528.60
- famhist  1   83.331 533.81
- age      1   84.416 539.79
> summary(sa.heart.step)

Call:
glm(formula = chd ~ tobacco + ldl + famhist + typea + obesity + 
    age, data = SAheart)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-0.8018  -0.3252  -0.1080   0.3861   1.0362  

Coefficients:
                Estimate Std. Error t value Pr(>|t|)    
(Intercept)    -0.395226   0.161401  -2.449 0.014713 *  
tobacco         0.016664   0.004776   3.489 0.000532 ***
ldl             0.034655   0.010357   3.346 0.000888 ***
famhistPresent  0.171924   0.041126   4.180 3.49e-05 ***
typea           0.005877   0.002023   2.905 0.003856 ** 
obesity        -0.007962   0.005054  -1.575 0.115856    
age             0.007953   0.001636   4.861 1.61e-06 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for gaussian family taken to be 0.1763702)

    Null deviance: 104.589  on 461  degrees of freedom
Residual deviance:  80.248  on 455  degrees of freedom
AIC: 518.4

Number of Fisher Scoring iterations: 2

**Comment by valafeli** [comment]
Zusammenhang Alkohol und Herzinfarkt -anscheinend U-Förmig

[https://www.aerztezeitung.de/medizin/krankheiten/herzkreislauf/article/906954/alkohol-gesundheit-aufs-herz.html](https://www.aerztezeitung.de/medizin/krankheiten/herzkreislauf/article/906954/alkohol-gesundheit-aufs-herz.html)
